### ISSUE TITLE
release.yml publishes :<ver>-cpu as a multi-arch manifest, contradicting the single-platform tag model the README documents

### ISSUE THREAD

**Issue by attevon-admin** [attevon-llc/diar-native#20]
## Summary

`.github/workflows/release.yml` builds `docker/Dockerfile.server-cpu` with `platforms: linux/amd64,linux/arm64` under a **single tag** (`:<ver>-cpu`), producing a **multi-arch manifest list**.

The README's "Published images" table, `docker-compose.prod.yml` and `start.sh` all assume the opposite: that **every tag is single-platform**, with arm64 living at its own `:<ver>-cpu-arm64` tag.

Both models are defensible. Shipping both at once is not.

## How it surfaced

0.3.0's arm64 image was pushed **by hand** as `:0.3.0-cpu-arm64` rather than by the workflow, so the published reality is currently single-platform:

```
davidamacey/diar-native:0.3.0                 amd64   (CUDA + CPU)
davidamacey/diar-native:latest                amd64   (CUDA + CPU)
davidamacey/diar-native:0.3.0-cpu             amd64
davidamacey/diar-native:0.3.0-cpu-arm64       arm64
davidamacey/diar-native:0.3.0-provision       amd64
davidamacey/diar-native:0.3.0-provision-arm64 arm64
```

If the workflow ran on the next tag, `:<ver>-cpu` would become a manifest list and `:<ver>-cpu-arm64` would not be produced at all — silently breaking `docker-compose.prod.yml` and `start.sh`'s arch selection, both of which reference the `-arm64` suffix by name.

## The two options

**A. Make the tags genuinely multi-arch** (manifest lists for `:latest`, `:<ver>` and `:<ver>-cpu`).
- `docker pull` picks the right architecture automatically — the behaviour users expect.
- Removes the sharp edge where an arm64 host pulling `:latest` silently gets an amd64 image.
- **But**: `:latest` and `:<ver>` are the CUDA superset, which is **amd64-only** (no aarch64 ONNX Runtime GPU build exists — #4). So those two tags cannot be honestly multi-arch unless the arm64 entry is the CPU image, which would mean one tag with materially different capabilities per architecture. That is arguably worse than the current explicitness.
- Practical shape: make `:<ver>-cpu` multi-arch (both platforms are genuinely the same build), keep `:<ver>`/`:latest` amd64-only and say so.

**B. Keep single-platform tags** and change `release.yml` to emit `:<ver>-cpu` (amd64) and `:<ver>-cpu-arm64` separately.
- Matches what is published today and what the docs, compose file and `start.sh` already assume.
- Keeps capability explicit in the tag name.
- **But**: `docker pull …:latest` on arm64 keeps doing the wrong thing for anyone not using `start.sh`.

Option A-for-the-CPU-tag-only is probably right: `:<ver>-cpu` is the one tag where both architectures are the same thing, so a manifest list is honest there. `:latest` and `:<ver>` stay amd64 and the README keeps saying so.

## Note on how this was found

Found while building the no-clone deployment path, by reading `release.yml` against the published tags rather than assuming they agreed. The workflow has not run for a release yet — 0.3.0's images were all built and pushed manually — so this has never actually fired. It would have fired on the next tag push.

## Acceptance

- [ ] `release.yml` and the published tag set agree, whichever model is chosen
- [ ] README "Published images", `docker-compose.prod.yml` and `start.sh`'s arch selection all match that model
- [ ] A tag push produces every tag the docs reference — including the provisioning images (`:<ver>-provision`, `:<ver>-provision-arm64`), which the workflow does not currently build at all
- [ ] If `:latest` stays amd64-only, the README says so where someone about to `docker pull` will read it

**Comment by attevon-admin** [comment]
Resolved, though not the way this issue proposed. Closing.

## What changed

`.github/workflows/release.yml` has been **removed** (`ef4ab0c`) and replaced by **`scripts/release.sh`**, which builds, scans and publishes locally.

The operator's call, and the evidence supports it: GitHub-hosted runners give ~14 GB of disk, while a release is five images across two architectures with the CUDA image alone at ~3 GB. That workflow was never viable there. It ran exactly once — on the `v0.3.0` tag push — and failed in 12 s at its credentials gate, before it could discover the disk problem. Every 0.3.0 image was built and pushed by hand.

So the underlying defect this issue named is gone, because the artifact that contained it is gone.

## The reasoning developed here survives intact

The tag model is unchanged and now lives in README "Published images", enforced by the script:

- `:latest` / `:<ver>` stay **amd64-only** — they are the CUDA superset, and no aarch64 ONNX Runtime GPU build exists (#4), so the only arm64 entry they could carry is the CPU image. One tag with different capabilities per architecture is worse than being explicit.
- `:<ver>-cpu` / `:<ver>-provision` are the same build with the same capabilities on both architectures.
- **`:<ver>-cpu-arm64` / `:<ver>-provision-arm64` are retained rather than dropped**, for a reason worth recording: all six published 0.3.0 tags are plain single-platform manifests and every doc pins 0.3.0. Dropping the aliases would make the README, compose file and `start.sh` wrong *today* and only right after the next release. Keeping them means every statement is true now and later, with no flag day.

The other half of this issue — that the workflow **did not build the provisioning images at all** — is also fixed: `scripts/release.sh` builds all five. That mattered because the serving images contain no Python, so `provision-models` against them exits 6, and `docker-compose.prod.yml` defaults its provision service to `:<ver>-provision`.

## Three checks the script makes that a workflow could not

1. **Refuses if `vendor/speakrs` has drifted from `patches/0001-*.patch`.** The patch set lives as an *uncommitted* diff in the working tree, so the machine that makes a vendored change is the one machine that cannot see a broken bootstrap.
2. **Asserts the binary reports the version being released** — catches an un-bumped crate version before it reaches a registry rather than after.
3. **Verifies published digests against the registry**, not the local daemon. A local tag proves nothing about what a stranger pulls.

Plus: clean tree required, architecture must match tag name, non-root asserted, and any HIGH/CRITICAL trivy finding fails the release across all five images. `--push` is explicit, because a tag someone has already pulled cannot be un-pulled.

## The most valuable thing this issue produced was unrelated to it

Validating the workflow required a real build, and that build revealed **`main` could not be compiled at all**:

```
error[E0560]: struct `RuntimeConfig` has no field named `fbank_pool`
```

`scripts/bootstrap_vendor_speakrs.sh` never applied the patch set, *and* pinned the wrong base — fork master `725cc4d`, when the patch is generated against upstream `b0756b1` and applies only there. Two contradictory reproduction stories for one tree, harmless until `be11492` made `diar-core` require a patched speakrs for the first time.

It was invisible locally, because a developer's working tree already carries the change as an uncommitted vendored diff. Only a clean clone or CI could see it — and CI had been red since `be11492`.

Fixed in `8d082b3`: bootstrap now checks out `b0756b1`, applies the patch, and fails loudly if it does not apply. A fresh clone builds in 42.6 s and CI is green again.

Also worth noting the workflow **failed correctly**: its "require credentials before doing any work" gate fired before checkout, QEMU or any build, so it never wasted 20 minutes building images it could not push. That behaviour is preserved in the script's preflight.
